### PR TITLE
[Changelog] Update master for Gaprindashvili Beta1

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot assign carbonin

**Comment by JPrause** [comment]
@miq-bot assign carbonin

**Comment by carbonin** [comment]
@JPrause We don't track ManageIQ releases in the container repos so it doesn't make much sense to list a Gaprindashvili version in the changelog when we are not releasing a Gaprindashvili version from this repo. We need a real versioning scheme for this repo going forward. /cc @Fryguy

Closing this.

**Pull request closed without merging**
